CREATE TABLE ESTADO (SIGLAUF CHAR(2), NOMEUF VARCHAR(100), PRIMARY KEY (SIGLAUF));

CREATE TABLE ATLETA (CODAT INT, NOMAT VARCHAR(100), SIGLAUF CHAR(2),  PRIMARY KEY (CODAT),
FOREIGN KEY (SIGLAUF) REFERENCES ESTADO (SIGLAUF));

CREATE TABLE PATROCINADOR (CODPAT INT, NOMPAT VARCHAR(100), PRIMARY KEY(CODPAT));

CREATE TABLE ATLETA_PAT (CODAT INT, CODPAT INT, VAL_PAT NUMERIC (12,2), PRIMARY KEY (CODAT, CODPAT),
FOREIGN KEY (CODAT) REFERENCES ATLETA(CODAT),
FOREIGN KEY (CODPAT) REFERENCES PATROCINADOR(CODPAT));

INSERT INTO ESTADO VALUES ('SP', 'SÃO PAULO');
INSERT INTO ESTADO VALUES ('RJ', 'RIO DE JANEIRO');

INSERT INTO ATLETA VALUES (1,'AURÉLIO MIGUEL','SP');
INSERT INTO ATLETA VALUES (2,'GUSTAVO BORGES','RJ');
INSERT INTO ATLETA VALUES (3,'ROBSON CAETANO','RJ');

INSERT INTO PATROCINADOR VALUES (2,'LACTA');
INSERT INTO PATROCINADOR VALUES (4,'NESTLE');
INSERT INTO PATROCINADOR VALUES (5,'UNIÃO');

INSERT INTO ATLETA_PAT (CODAT,CODPAT,VAL_PAT) VALUES (1,2,'60000.00');
INSERT INTO ATLETA_PAT (CODAT,CODPAT,VAL_PAT) VALUES (1,4,'53000.00');
INSERT INTO ATLETA_PAT (CODAT,CODPAT,VAL_PAT) VALUES (2,2,'30000.00');
INSERT INTO ATLETA_PAT (CODAT,CODPAT,VAL_PAT) VALUES (2,4,'22000.00');
INSERT INTO ATLETA_PAT (CODAT,CODPAT,VAL_PAT) VALUES (3,4,'43000.00');
INSERT INTO ATLETA_PAT (CODAT,CODPAT,VAL_PAT) VALUES (3,5,'16000.00');
